### ISSUE TITLE
版本升级

### ISSUE THREAD

**Issue by tanjwGit** [react-native-hero/umeng-analytics#1]
1. 新版本友盟稳定性被独立出来了；
2. 友盟推送部分厂商push可以更新支持安卓11

**Comment by musicode** [comment]
最近找个时间升级，到时候我会在这说

**Comment by tanjwGit** [comment]
@musicode 谢谢你如此迅速的升级了本库，但我觉得还有以下几点事情需要做：
1. 我注意到了你引入了友盟预初始化preInit，根据去年工信部合规审查经验及友盟文档, preInit在用户启动app时进行预初始化，必须到用户同意使用协议过后才能进行初始化（正是这么做的才通过了审查，ios不受此限制仅android），因此对于纯rn应用来说，init应当暴露给rn在js中合适的位置调用。
2. 对于react-native-hero/umeng-push，只升级了友盟库，各厂商通道并没有升级版本。
3. 更新使用文档示例。

**Comment by musicode** [comment]
1. 我考虑到兼容旧版本，暂时没做调用上的改动
2. 我本来想去升级厂商，没在文档里找到对应的部分，我再找找

下个版本，我给两个库都加一个 init 让 js 调用吧

**Comment by musicode** [comment]
react-native-hero/umeng-push@0.1.4  升级了友盟最新版本

加 init 方法的问题，我再考虑一下怎么实现比较好

**Comment by tanjwGit** [comment]
@musicode 对了，注意一下这两个链接
1. https://developer.umeng.com/docs/119267/detail/182050#TCM7O
2. https://developer.umeng.com/docs/67966/detail/187200
我是在预初始化时传入metaData等需要的数据并保存起来， js调用init时直接读取使用，几个月以来看上去可以正常工作（至少推送消息是正常的， 我只使用了最基本的功能），但是不知这样是否合适

**Comment by jlala** [comment]
请问合规问题 react-native 怎么做到用户手动同意后在初始化友盟？

**Comment by tanjwGit** [comment]
> 请问合规问题 react-native 怎么做到用户手动同意后在初始化友盟？

1. 在MainApplication.java中进项预初始化
2. 点击同意后在调用初始化函数

**Comment by musicode** [comment]
这个库不支持预初始化，试过，友盟 sdk 有 bug，可能会有潜在的各种问题，半年或一年后，等友盟 sdk 完善了再说

**Comment by jlala** [comment]
那app怎么通过 应用宝的审核呢？

**Comment by jlala** [comment]
不过是不是可以在用户同意隐私条款之后，在调用new push 实例？

**Comment by musicode** [comment]
安卓有些敏感权限，是需要用户手动点击授权的，你用 react-native-permissions 去申请 `READ_PHONE_STATE` 和 `WRITE_EXTERNAL_STORAGE` 权限就行了，底层该怎么初始化还是怎么初始化，只是可能没权限有些功能用不了

**Comment by kangfenmao** [comment]
> 1. 我考虑到兼容旧版本，暂时没做调用上的改动
> 2. 我本来想去升级厂商，没在文档里找到对应的部分，我再找找
> 
> 下个版本，我给两个库都加一个 init 让 js 调用吧

我们的应用也是被Android隐私协议卡住了，如果有单独的 init 函数就好了 @musicode

**Comment by kangfenmao** [comment]
![image](https://user-images.githubusercontent.com/8253512/122500078-a9bbf680-d024-11eb-946d-c3ea965d1408.png)

**Comment by kangfenmao** [comment]
![image](https://user-images.githubusercontent.com/8253512/126289813-898c73b3-2abc-4a9a-a4a0-5cc13c8f9b8c.png)
![image](https://user-images.githubusercontent.com/8253512/126289852-45ebd011-b8a5-4aed-b40d-48589c0c66d3.png)

**Comment by musicode** [comment]
我不确定这样写有没有问题，但这样的确是改动最小的方案，你可以先试试，没问题可以来这说一下，我发新版同步你的改动

**Comment by musicode** [comment]
之前的方案是官方提供的 preInit 方法，我最后一次尝试它时，连推送都挂了，因此放弃

**Comment by kangfenmao** [comment]
等我明天在我们项目测试一下，目前没有使用推送，我先测试一下统计会不会有问题 @musicode

**Comment by kangfenmao** [comment]
此改动有效，应用商店审核没有提出关于本库隐私协议问题

patch 文件：

[@react-native-hero.zip](https://github.com/react-native-hero/umeng-analytics/files/6867699/%40react-native-hero.zip)

另外：

1. 建议增加 preInit 函数在 onCreate 函数中调用

@musicode

**Comment by musicode** [comment]
加 preInit 是否会引起推送异常我还要观察一下

**Comment by kangfenmao** [comment]
> 加 preInit 是否会引起推送异常我还要观察一下

下周我试试看

**Comment by musicode** [comment]
宣布一个好消息，`umeng-push` 和 `umeng-analytics` 两个库都支持了 preInit 了，现在可以用原生 `init` 做预初始化，js 的 `init` 做真正的初始化，之前说的推送可能有问题，新版本也解决了

业务层的改动，请参考 readme 的改动
