### ISSUE TITLE
enterPage leavePage 传入字符串后，后台显示的问题

### ISSUE THREAD

**Issue by KokoTa** [react-native-hero/umeng-analytics#4]
![image](https://user-images.githubusercontent.com/14892053/196137861-54d10e35-3e67-47dc-aed1-9cc91d60bcb4.png)
<img width="719" alt="image" src="https://user-images.githubusercontent.com/14892053/196138727-5f500fb8-8798-4e1d-9af5-d5e2cfd1bb35.png">
您好，我使用该插件后，enterPage 传入 ’Login‘ ‘Trending’ 等字符串，但是后台显示 1-2 3-5，请问这是正常显示吗？

"react-native": "0.70.1"
"@react-native-hero/umeng-analytics": "^0.2.0"

平台为 IOS

**Comment by musicode** [comment]
我的后台也是 1-2 3-5 这样的数字，我去问问友盟开发吧

**Comment by musicode** [comment]
Q: 页面访问记录，为什么没有页面名称，只有 1-2 这样的数字呢？我调接口的时候是传了英文名的
A：这是访问页面数得分布情况，比如访问了1-2个页面得启动次数：1200，展示该时段内用户一次启动内访问1-2个页面的启动总次数。
Q：那我怎么知道 A 页面访问了多少次，B 页面访问了多少次呢？
A：移动统计里面是没有这个统计指标得，如想实现A页面访问了多少次，建议使用自定义事件进行埋点跟踪，看是否满足您的需求，自定义事件：https://developer.umeng.com/docs/119267/detail/118637
